<a href="https://colab.research.google.com/github/itzshubham06/Python-Programs/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as n
l1=[12,333,42,34.54,344,4633,6745]
print(l1)
arr=n.array(l1)
print(arr)

[12, 333, 42, 34.54, 344, 4633, 6745]
[  12.    333.     42.     34.54  344.   4633.   6745.  ]


In [ ]:
import numpy as np
l2=[[12,34,46,45],[12,34,56563,443]]
print(l2)
arr1=np.array(l2)
print(arr1)

[[12, 34, 46, 45], [12, 34, 56563, 443]]
[[   12    34    46    45]
 [   12    34 56563   443]]


In [ ]:
import numpy as np
l3=[[12,23,45,56,56],[12,23,34,45,657],[12,23,435,56,67]]
print(l3)
arr2=np.array(l3)
print(arr2)

[[12, 23, 45, 56, 56], [12, 23, 34, 45, 657], [12, 23, 435, 56, 67]]
[[ 12  23  45  56  56]
 [ 12  23  34  45 657]
 [ 12  23 435  56  67]]


In [ ]:
import numpy as np
arr3=np.arange(0,10+1)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np
arr4=np.arange(11,19+1).reshape(3,3)
print(arr4)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
import numpy as np
arr5 = np.arange(11,20).reshape(3,3)
print(arr5)
print(arr5.dtype)
print(arr5.ndim)
print(arr5.size)
print(arr5.itemsize)
print(arr5.shape)
arr6=np.arange(1,10)
print(arr6)
print(arr6.dtype)
print(arr6.ndim)
print(arr6.size)
print(arr6.itemsize)
print(arr6.shape)

arr7=np.arange(1,5).reshape(2,2)
print(arr7)
print(arr7.dtype)
print(arr7.ndim)
print(arr7.size)
print(arr7.itemsize)
print(arr7.shape)


[[11 12 13]
 [14 15 16]
 [17 18 19]]
int64
2
9
8
(3, 3)
[1 2 3 4 5 6 7 8 9]
int64
1
9
8
(9,)
[[1 2]
 [3 4]]
int64
2
4
8
(2, 2)


In [ ]:
import numpy as np
arra1=np.array([10,20,30,40,50,60,70])
print(arra1[1:2])
print(arra1[1:6:2])
print(arra1[-1:-3:-1])
print(arra1[::2])

[20]
[20 40 60]
[70 60]
[10 30 50 70]


In [ ]:
import numpy as np
array2=np.array([[15,16,17],[25,26,27],[35,36,37],[45,46,47]])
print(array2[1,])
print()
print(array2[:,1])
print()
print(array2[1:3,1:3])
print()
print(array2[:,1:3])
print()
print(array2[1:3,1])
print()
print(array2[1:3,:1])
print()
print(array2[0,1:3])
print()
print(array2[:,1])
print()
print(array2[:,2])
print()
print(array2[1,:])
print(array2.max())


[25 26 27]

[16 26 36 46]

[[26 27]
 [36 37]]

[[16 17]
 [26 27]
 [36 37]
 [46 47]]

[26 36]

[[25]
 [35]]

[16 17]

[16 26 36 46]

[17 27 37 47]

[25 26 27]
47


In [ ]:
s1="SBJAIN college 54678"
print(s1)
cspace=0
cdigit=0
calphabet=0
for i in s1:
  if i.isspace():
    cspace+=1
  if i.isdigit():
    cdigit+=1
  if i.isalnum():
    calphabet+=1
print("String =",s1)
print("Space =",cspace)
print("Digit =",cdigit)
print("Alphabet =",calphabet)
print(s1.count("s"))

SBJAIN college 54678
String = SBJAIN college 54678
Space = 2
Digit = 5
Alphabet = 18
0


In [ ]:
s="welcome to python programming"
print(s.find("p"))#find first index  position of p ie: 11
print(s.index("p"))#also same
print(s.find("p",12))#find p from 12 index to end
print(s.index("p",12))#same like find
print(s.find("p",1,13))#find p from 1 to 12 index
print(s.index("p",1,13))#same like find
#difference in both
print(s.find("k"))  #give -1
# print(s.index("k")) #give error value error because "k" is in string
print(s.strip())

11
11
18
18
11
11
-1
welcome to python programming


In [ ]:
s="welcome to python language"
print(s.count("e")) #3 times toatl count
print(s.count("e",5)) #start count from 5 to end so 2
"""
"""
#split,partition
s="welcome to all python programming "
print(s.split()) #by default split from space and return answer in list
print(s.split("p"))#jaha jaha p waha , ayega
#partition
#print(s.partition())#here must give value for partion nahi tao error
print(s.partition("p"))
#p ke pahele ek part,then  p,then baki part give answer in tupple
#output=>('welcome to all ', 'p', 'ython programming ')
#jony jony wal aexample


3
2
['welcome', 'to', 'all', 'python', 'programming']
['welcome to all ', 'ython ', 'rogramming ']
('welcome to all ', 'p', 'ython programming ')


In [ ]:
s1=" sbjain"
print(s1)# its print as it is
print(s1.lstrip())#remove left space
#rstrip
s2="sbjain     "
print(s2)
print(s2.rstrip())#its remove but nor see
#to see rstrip
s3="sbjain     "
print(len(s3))#its count all
print(len(s3.rstrip()))#after remove ight space
#strip remove both side space
"""
"""
#endswith,startwith,join,replace
s="Python welcome to python"
print(s.endswith("n"))#true
print(s.startswith("w"))#true
#join
print(" ".join(s))#join with each word
print(s.replace("python","java"))

 sbjain
sbjain
sbjain     
sbjain
11
6
True
False
P y t h o n   w e l c o m e   t o   p y t h o n
Python welcome to java


In [ ]:
#access and print characters form string
str="HELLO PYTHON"
for i in str:
  print(i,end=" ")

H E L L O   P Y T H O N 

In [ ]:
#print a string and extract chatacters from string
str="Python Programming"
print(str)
for ch in str:
  print(ch)

Python Programming
P
y
t
h
o
n
 
P
r
o
g
r
a
m
m
i
n
g


In [ ]:
#print words wits their length of a string
str="String is mutable"
lst=str.split()
print(lst)


['String', 'is', 'mutable']


In [ ]:
import math as np
lst=[]
print(lst)
for i in range(1,10):
  lst.append(i)
print(lst)
print(np.fsum(lst))

[]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
45.0


In [ ]:
lst=[1,"hindi",33,44,"eduskill"]
print(lst[::1])


[1, 'hindi', 33, 44, 'eduskill']


In [ ]:
l1=[11,22,33,44]
l2=[1,2,3,4]
print(l1)
print(l2)
l3=l1+l2
print(l3)
l3.sort()
print(l3)
print("lentgth of list 1 :",len(l1))
print("lentgth of list 2 :",len(l2))
print("lentgth of list 3 :",len(l3))
l3.append(9)
print("Appended List:",l3)
l3.extend([1,2,3,4,4,5,6])
print("Extendet list:",l3)
l3.sort()
print("Sorted list:",l3)
l2.insert(-1,12)
print(l2)
l2.pop()
print(l2)
l2.remove(1)
print(l2)
l1.reverse()
print(l1)
l2.clear()
print(l2)

[11, 22, 33, 44]
[1, 2, 3, 4]
[11, 22, 33, 44, 1, 2, 3, 4]
[1, 2, 3, 4, 11, 22, 33, 44]
lentgth of list 1 : 4
lentgth of list 2 : 4
lentgth of list 3 : 8
Appended List: [1, 2, 3, 4, 11, 22, 33, 44, 9]
Extendet list: [1, 2, 3, 4, 11, 22, 33, 44, 9, 1, 2, 3, 4, 4, 5, 6]
Sorted list: [1, 1, 2, 2, 3, 3, 4, 4, 4, 5, 6, 9, 11, 22, 33, 44]
[1, 2, 3, 12, 4]
[1, 2, 3, 12]
[2, 3, 12]
[44, 33, 22, 11]
[]


In [ ]:
t=tuple("Hello")
print(t)

('H', 'e', 'l', 'l', 'o')


In [ ]:
L=['a','e','i','o','u']
T=tuple(L)
print(T)

('a', 'e', 'i', 'o', 'u')


In [ ]:
t=tuple(input("Enter tuple elements:"))
print(t)

Enter tuple elements:12345676
('1', '2', '3', '4', '5', '6', '7', '6')


In [ ]:
t=eval(input("Enter tuple elements:"))
print(t)

Enter tuple elements:1.1,21,"hell"
(1.1, 21, 'hell')


In [ ]:
t=(12)
print(t)
t=tuple()
print(t)

12
()


In [ ]:
t=(1,2,3,4)
print(t)
t=(1.2,1.2,1.4,"a")
print(t)
#nested tuple
t=(1,2,3,(44,55))
print("NESTED TUPPLE=>",t)

(1, 2, 3, 4)
(1.2, 1.2, 1.4, 'a')
NESTED TUPPLE=> (1, 2, 3, (44, 55))


In [ ]:
l=[1,2,3]
print(tuple(l))
s="python"
print(tuple(s))
#conver dic to tuple
d={1:"a",2:"b",3:"c"}
print(tuple(d))  #by default key
print(tuple(d.values()))


(1, 2, 3)
('p', 'y', 't', 'h', 'o', 'n')
(1, 2, 3)
('a', 'b', 'c')


In [ ]:
t=(1,23,45,676,897,465)
print(t)
for i in t:
  print(i)

(1, 23, 45, 676, 897, 465)
1
23
45
676
897
465


In [ ]:
str="RESPONSIBILITY"
print(str)
tup=tuple(str)
print("String is Converted into Tuple:")
print(tup)
print("The converted string in Tuple accessed one by one:")
for i in tup:
  print(i,end="-")


RESPONSIBILITY
String is Converted into Tuple:
('R', 'E', 'S', 'P', 'O', 'N', 'S', 'I', 'B', 'I', 'L', 'I', 'T', 'Y')
The converted string in Tuple accessed one by one:
R-E-S-P-O-N-S-I-B-I-L-I-T-Y-

In [ ]:
t=(11,22,33,44,55,66,77)
print(t[0])
print(t[-1])
print(t[-4])
print('Tuple elements are:',t)

11
77
44
Tuple elements are: (11, 22, 33, 44, 55, 66, 77)


In [ ]:
t=(1,2)
print(any(t))
t=()
print(any(t))
print()

t=(True,True,False)
print(all(t))
t=(1,2,3 )
print(all(t))
print("Length of Tuple:",len(t))
print("Sum of Tuple Elements:",sum(t))
print(sorted(t))
print("Maximum",max(t))
print("Minimum:",min(t))


True
False

False
True
Length of Tuple: 3
Sum of Tuple Elements: 6
[1, 2, 3]
Maximum 3
Minimum: 1


In [ ]:
#Create a tuple with three elements: 10, “hello”, and 3.14.
t=(10,"hello",3.14)
print("Tuple Elements :",t)

Tuple Elements : (10, 'hello', 3.14)


In [ ]:
#Given the tuple (1, 2, 3, 4, 5), access and print the third element
t=(1,2,3,4,5)
print(t[3])

4


In [ ]:
#Concatenate the tuples (1, 2, 3) and (4, 5, 6) and store the result in a new tuple.
t1=(1,2,3)
t2=(4,5,6)
print("Tuple 1:",t1)
print("Tuple 2:",t2)
t3=t1+t2
print("Concatenated Tuple:",t3)

Tuple 1: (1, 2, 3)
Tuple 2: (4, 5, 6)
Concatenated Tuple: (1, 2, 3, 4, 5, 6)


In [ ]:
dic={ }
print(dic)
print(type(dic))
d=dict()
print(d)
print(type(d))
d={1:"x",2:"y",3:"z"}
print(d)
print(d.keys())
print(d.values())
print(d.items())

{}
<class 'dict'>
{}
<class 'dict'>
{1: 'x', 2: 'y', 3: 'z'}
dict_keys([1, 2, 3])
dict_values(['x', 'y', 'z'])
dict_items([(1, 'x'), (2, 'y'), (3, 'z')])


In [ ]:
d1= {"a":"apple","b":"orange","c":"mango"}
d2=dict(a="apple",b="orange",c="mango")
d3=dict([("a","apple"),("b","orange"),("c","mango")])
d4=dict({"a":"apple","b":"orange","c":"mango"})
print(d1==d2==d3==d4)


True


In [ ]:
d1={1:99,2:67,3:55}
d2={1:99,2:67,3:55}
print(d1==d2)
d={1:"DD",2:"MM",3:"YY"}
print(d[1])


True
DD


In [ ]:
d1=dict()
d1[1]="one"
d1[2]="two"
d1[3]="three"
d1[4]="four"
print(d1)

{1: 'one', 2: 'two', 3: 'three', 4: 'four'}


In [ ]:
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
for i in d:
    print(i,end=" ")
print()
for i in d:
    print(d[i],end=" ")
print()
for i in d.values():
    print(i,end=" ")
print()
for i in d:
    print("key=>",i,"value=>",d[i])

1 2 3 4 
one two three four 
one two three four 
key=> 1 value=> one
key=> 2 value=> two
key=> 3 value=> three
key=> 4 value=> four


In [ ]:
d1={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
d2={5:"five"}
d1.update(d2)
print(d1)
print(d2)
d1={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
del d1[1]
print(d1)
del(d1)
print(d)
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
d.pop(1)
print(d)
#print(d.pop())

{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}
{5: 'five'}
{2: 'two', 3: 'three', 4: 'four'}
{2: 'two', 3: 'three', 4: 'four'}
{2: 'two', 3: 'three', 4: 'four'}


In [ ]:
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
print(1 in d)
print(1 in d.values())


True
False


In [ ]:
s = "Hello"
s += " World"
print(s)

Hello World
